# Generated by Django 4.2.27 on 2026-01-31 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0010_alter_homeappointment_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAppointmentKaspiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('payment_id', models.CharField(max_length=64, unique=True, verbose_name='ID платежа Kaspi')),
                ('mpp_payment_id', models.CharField(max_length=64, verbose_name='ID в системе ZhanCare')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('cancelled', 'Отменено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('receipt_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на чек (Kaspi)')),
                ('receipt_pdf', models.URLField(blank=True, null=True, verbose_name='PDF чека (Kaspi)')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_payment', to='appointments.homeappointment', verbose_name='Вызов на дом')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_home_payments', to=settings.AUTH_USER_MODEL, verbose_name='Клиент (Пациент)')),
            ],
            options={
                'verbose_name': 'Платеж Kaspi',
                'verbose_name_plural': 'Платежи Kaspi',
                'db_table': 'payments_kaspi_home_appointments',
                'ordering': ['-created_at'],
            },
        ),
    ]
