"""
Django settings for mchs_back project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-emst*q@f==ek=8-o)me!_l1ek2vi*#_s9g46d6+86*nlbvstms"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.vercel.app', 'exp-admin.smartalmaty.kz']

# Application definition

INSTALLED_APPS = [
    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "drf_yasg",  # Make sure drf-yasg is listed
    # Third-party apps
    "daphne",  # ✅ ASGI server for Django
    "channels",
    "django.contrib.staticfiles",
    "rest_framework",  # Django REST Framework for APIs
    "rest_framework.authtoken",  # Token-based authentication (optional)
    "corsheaders",  # For handling Cross-Origin Resource Sharing (CORS)
    "drf_spectacular",
    # Apps
    "common",  # Your custom app
    "appointments",
    "consultations",
]

APPEND_SLASH = False  # Disable appending slashes to URLs

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Add this at the top
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mchs_back.urls"

SPECTACULAR_SETTINGS = {
    'TITLE': 'ZhanCareAI API',
    'DESCRIPTION': 'API documentation for ZhanCareAI backend',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    'COMPONENT_SPLIT_REQUEST': True,  # (optional, делает схемы красивее)
    
    'SECURITY': [
        {'BearerAuth': []},
    ],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
}



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'common.authentication.CustomTokenAuthentication',  # ✅ Use your CustomToken
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
}



# Restrict Access-Control-Allow-Origin to a specific domain Production
# CSRF_TRUSTED_ORIGINS = [
#     'https://api.testfront.csti.kz',
#     'https://testfront.csti.kz',
#     'https://85.202.192.35',
#     'https://api.csti.kz',
#     'https://csti.kz',
# ]

# Для использования на локалхосте закоментить CORS_ALLOWED_ORIGINS и раскоментить CORS_ALLOW_ALL_ORIGINS и сделать = True
# Ensure wildcard (*) is NOT used together with specific origins
CORS_ALLOW_ALL_ORIGINS = True  # Set this to False if not already 

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:5173',
    'http://127.0.0.1:8000/',
    'https://exp-admin.smartalmaty.kz',
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = "mchs_back.wsgi.application"
ASGI_APPLICATION = "mchs_back.asgi.application"


# ✅ (Optional) Use Redis for WebSockets (better for production)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'db_core',
        'USER': 'itry',
        'PASSWORD': 'admin123456@',
        'HOST': '10.100.200.150',
        'PORT': '5439',
    }
}

MISTRAL_API_KEY="QqkMxELY0YVGkCx17Vya04Sq9nGvCahu"

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': 'zhancare_db',
#         'USER': 'zhancare',
#         'PASSWORD': '4HPzQt2HyU',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

LIVEKIT_URL="wss://zhancare-4yvomh3h.livekit.cloud"
LIVEKIT_API_KEY="APIsH5RHgRW6vdD"
LIVEKIT_API_SECRET="HRlbQpMWWHBzrxgAFReeVaTV0X3fA6UMO5uP4rdMp1hA"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'marzipan9256@yandex.com'
EMAIL_HOST_PASSWORD = 'deecnwsrkvczrcqf'
DEFAULT_FROM_EMAIL = 'ZhanCare.Ai <marzipan9256@yandex.com>'