# Generated by Django 5.1.2 on 2024-10-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModulesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_kz', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория модуля',
                'verbose_name_plural': 'Категории модулей',
                'db_table': 'modules_category',
            },
        ),
        migrations.CreateModel(
            name='ModulesSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_kz', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_category_id', to='modules.modulescategory', verbose_name='Категория модуля')),
            ],
            options={
                'verbose_name': 'Подкатегория модуля',
                'verbose_name_plural': 'Подкатегории модулей',
                'db_table': 'modules_sub_category',
            },
        ),
    ]
