# Generated by Django 5.1.2 on 2024-10-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulessubcategory',
            name='module_category',
        ),
        migrations.DeleteModel(
            name='ModulesCategory',
        ),
        migrations.DeleteModel(
            name='ModulesSubCategory',
        ),
    ]
