# Generated by Django 5.1.2 on 2024-10-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulessubcategory',
            name='name_en',
        ),
    ]
