# Generated by Django 4.2.26 on 2025-11-22 14:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('address_comment', models.CharField(blank=True, max_length=512, null=True, verbose_name='Комментарий к адресу')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс')),
                ('microdistrict', models.CharField(blank=True, max_length=255, null=True, verbose_name='Микрорайон')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('administrative_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Административный округ')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='Часы работы')),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Часовой пояс')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг')),
                ('review_count', models.IntegerField(blank=True, null=True, verbose_name='Количество отзывов')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('vkontakte', models.CharField(blank=True, max_length=255, null=True, verbose_name='ВКонтакте')),
                ('viber', models.CharField(blank=True, max_length=255, null=True, verbose_name='Viber')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTube')),
                ('skype', models.CharField(blank=True, max_length=255, null=True, verbose_name='Skype')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Геолокация (Point, SRID=4326)')),
                ('gis2_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка 2ГИС')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип организации')),
                ('categories', models.JSONField(blank=True, null=True, verbose_name='Категории')),
                ('phones', models.JSONField(blank=True, null=True, verbose_name='Телефоны')),
                ('emails', models.JSONField(blank=True, null=True, verbose_name='Email адреса')),
                ('websites', models.JSONField(blank=True, null=True, verbose_name='Веб-сайты')),
                ('whatsapp', models.JSONField(blank=True, null=True, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
                'db_table': 'clinics',
            },
        ),
    ]
