# Generated by Django 4.2.26 on 2025-11-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='administrative_area',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Административный округ'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='city',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='country',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='district',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='facebook',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='instagram',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='microdistrict',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Микрорайон'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='name',
            field=models.CharField(db_index=True, max_length=512, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='region',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='skype',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='twitter',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='type',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='viber',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='vkontakte',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='working_hours',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='youtube',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='YouTube'),
        ),
    ]
