# Generated by Django 4.2.26 on 2025-11-22 15:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_add_city_and_district_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microdistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (рус)')),
                ('name_kz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (каз)')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Точка (центр микрорайона)')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326, verbose_name='Геометрия (границы)')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microdistricts', to='clinics.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Микрорайон',
                'verbose_name_plural': 'Микрорайоны',
                'db_table': 'microdistricts',
                'ordering': ['name_ru'],
            },
        ),
    ]
