# Generated by Django 4.2.26 on 2025-11-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_add_country_and_region_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='city_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='clinics.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='country_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='clinics.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='district_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='clinics.district', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='microdistrict_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='clinics.microdistrict', verbose_name='Микрорайон'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='region_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='clinics.region', verbose_name='Регион'),
        ),
    ]
