# Generated by Django 4.2.26 on 2025-11-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_clinics_city_fk_clinics_country_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinics',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clinics',
            name='country',
        ),
        migrations.RemoveField(
            model_name='clinics',
            name='district',
        ),
        migrations.RemoveField(
            model_name='clinics',
            name='microdistrict',
        ),
        migrations.RemoveField(
            model_name='clinics',
            name='region',
        ),
    ]
