# Generated by Django 4.2.26 on 2025-11-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_remove_clinics_city_remove_clinics_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinics',
            old_name='city_fk',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='clinics',
            old_name='country_fk',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='clinics',
            old_name='district_fk',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='clinics',
            old_name='microdistrict_fk',
            new_name='microdistrict',
        ),
        migrations.RenameField(
            model_name='clinics',
            old_name='region_fk',
            new_name='region',
        ),
    ]
