# Generated by Django 4.2.26 on 2025-12-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_rename_city_fk_clinics_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='is_deleted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
    ]
