# Generated by Django 5.1.2 on 2025-04-26 18:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_delete_consultation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалено"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название клиники"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Адрес"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Вебсайт"),
                ),
            ],
            options={
                "verbose_name": "Клиника",
                "verbose_name_plural": "Клиники",
            },
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалено"),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Опыт работы (лет)"
                    ),
                ),
                (
                    "clinics",
                    models.ManyToManyField(
                        blank=True,
                        related_name="doctors",
                        to="common.clinic",
                        verbose_name="Клиники",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль доктора",
                "verbose_name_plural": "Профили докторов",
            },
        ),
        migrations.CreateModel(
            name="DoctorSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалено"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Специализация"
                    ),
                ),
            ],
            options={
                "verbose_name": "Специализация врача",
                "verbose_name_plural": "Специализации врачей",
            },
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.RemoveField(
            model_name="customtoken",
            name="created",
        ),
        migrations.AddField(
            model_name="customtoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 4, 26, 18, 40, 47, 14233, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customtoken",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="customtoken",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to="common.user",
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.doctorspecialization",
            ),
        ),
    ]
