# Generated by Django 4.2.21 on 2025-05-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип врача'),
        ),
    ]
