# Generated by Django 4.2.23 on 2025-07-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_user_reset_code_user_reset_code_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Тип врача')),
            ],
            options={
                'verbose_name': 'Тип врача',
                'verbose_name_plural': 'Типы врачей',
                'db_table': 'common_doctor_types',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='doctor_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.doctortype', verbose_name='Тип врача'),
        ),
    ]
