# Generated by Django 4.2.23 on 2025-07-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_doctortype_user_doctor_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='doctor_types',
        ),
        migrations.AddField(
            model_name='user',
            name='doctor_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.doctorspecialization', verbose_name='Тип врача'),
        ),
    ]
