# Generated by Django 4.2.23 on 2025-07-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_user_doctor_types_user_doctor_specialization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorType',
        ),
    ]
