# Generated by Django 4.2.23 on 2025-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_delete_doctortype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorspecialization',
            name='name',
        ),
        migrations.AddField(
            model_name='doctorspecialization',
            name='name_en',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Specialization (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorspecialization',
            name='name_kz',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Специализация (KZ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorspecialization',
            name='name_ru',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Специализация (RU)'),
            preserve_default=False,
        ),
    ]
