# Generated by Django 4.2.23 on 2025-07-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_doctorspecialization_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctorspecialization',
            table='common_doctors_specialization',
        ),
    ]
