# Generated by Django 4.2.24 on 2025-09-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_customtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fluorography_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата флюорографии'),
        ),
        migrations.AddField(
            model_name='user',
            name='fluorography_status',
            field=models.CharField(blank=True, choices=[('normal', 'Норма'), ('abnormal', 'Отклонения'), ('pending', 'Ожидает результата'), ('expired', 'Просрочена')], max_length=20, null=True, verbose_name='Статус флюорографии'),
        ),
        migrations.AddField(
            model_name='user',
            name='immunization_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней иммунизации'),
        ),
        migrations.AddField(
            model_name='user',
            name='immunization_status',
            field=models.CharField(blank=True, choices=[('up_to_date', 'Актуальная'), ('partial', 'Частичная'), ('expired', 'Просрочена'), ('none', 'Отсутствует')], max_length=20, null=True, verbose_name='Статус иммунизации'),
        ),
        migrations.AddField(
            model_name='user',
            name='rhesus_factor',
            field=models.CharField(blank=True, choices=[('positive', 'Положительный'), ('negative', 'Отрицательный')], max_length=10, null=True, verbose_name='Резус-фактор'),
        ),
    ]
