# Generated by Django 4.2.11 on 2025-09-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_add_doctor_availability'),
        ('common', '0016_user_fluorography_date_user_fluorography_status_and_more'),
    ]

    operations = [
    ]
