# Generated by Django 4.2.11 on 2025-09-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_merge_20250922_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='availability_note',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='user',
            name='availability_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметка о доступности'),
        ),
        migrations.AddField(
            model_name='user',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available', 'Доступен'), ('busy', 'Занят'), ('offline', 'Не работает'), ('break', 'На перерыве')], max_length=20, null=True, verbose_name='Статус доступности'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний раз в сети'),
        ),
    ]
