# Generated by Django 4.2.11 on 2025-09-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_move_availability_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available', 'Доступен'), ('busy', 'Занят'), ('offline', 'Не работает'), ('break', 'На перерыве')], default='offline', max_length=20, null=True, verbose_name='Статус доступности'),
        ),
    ]
