# Generated by Django 4.2.26 on 2025-11-15 09:01

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_add_default_availability_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('name_ru', models.CharField(max_length=255, unique=True, verbose_name='Специализация (RU)')),
                ('name_kz', models.CharField(max_length=255, unique=True, verbose_name='Специализация (KZ)')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='Specialization (EN)')),
            ],
            options={
                'verbose_name': 'Специализация медсестры',
                'verbose_name_plural': 'Специализации медсестёр',
                'db_table': 'common_nurses_specialization',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', common.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='nurse_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип медсестры'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Пациент'), ('doctor', 'Доктор'), ('nurse', 'Медсестра'), ('admin', 'Администратор')], default='patient', max_length=15, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Опыт работы (лет)')),
                ('clinics', models.ManyToManyField(blank=True, related_name='nurses', to='common.clinic', verbose_name='Клиники')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.nursespecialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль медсестры',
                'verbose_name_plural': 'Профили медсестёр',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='nurse_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.nursespecialization', verbose_name='Специализация медсестры'),
        ),
    ]
