# Generated by Django 4.2.26 on 2025-12-05 09:43
# Migration to transfer tokens from CustomToken to DRF Token

from django.db import migrations


def migrate_custom_tokens_to_drf(apps, schema_editor):
    """
    Migrate tokens from common_authtoken (CustomToken) to authtoken_token (DRF Token)
    """
    from django.db import connection

    with connection.cursor() as cursor:
        # Check if custom token table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_name = 'common_authtoken'
            );
        """)
        custom_token_exists = cursor.fetchone()[0]

        if not custom_token_exists:
            print("✅ Custom token table does not exist. Skipping migration.")
            return

        # Check if standard token table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_name = 'authtoken_token'
            );
        """)
        standard_token_exists = cursor.fetchone()[0]

        if not standard_token_exists:
            print("❌ Standard DRF token table does not exist yet.")
            print("   Run: python manage.py migrate authtoken first")
            return

        # Get all tokens from custom table
        cursor.execute("""
            SELECT key, user_id, created_at
            FROM common_authtoken
        """)
        custom_tokens = cursor.fetchall()

        print(f"📊 Found {len(custom_tokens)} custom tokens to migrate")

        if len(custom_tokens) == 0:
            print("✅ No tokens to migrate.")
            return

        # Migrate tokens
        migrated = 0
        skipped = 0
        errors = 0

        for key, user_id, created_at in custom_tokens:
            try:
                # Check if token already exists for this user in standard table
                cursor.execute("""
                    SELECT key FROM authtoken_token WHERE user_id = %s
                """, [user_id])

                existing = cursor.fetchone()

                if existing:
                    print(f"⚠️  Token already exists for user {user_id}, skipping...")
                    skipped += 1
                    continue

                # Insert token into standard DRF table
                cursor.execute("""
                    INSERT INTO authtoken_token (key, created, user_id)
                    VALUES (%s, %s, %s)
                    ON CONFLICT (user_id) DO NOTHING
                """, [key, created_at, user_id])

                print(f"✅ Migrated token for user {user_id}")
                migrated += 1

            except Exception as e:
                print(f"❌ Error migrating token for user {user_id}: {e}")
                errors += 1

        print("\n" + "=" * 80)
        print("MIGRATION SUMMARY")
        print("=" * 80)
        print(f"✅ Migrated: {migrated}")
        print(f"⚠️  Skipped: {skipped}")
        print(f"❌ Errors: {errors}")
        print(f"📊 Total: {len(custom_tokens)}")
        print("=" * 80)


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - copy tokens back from DRF to CustomToken
    (Only works if CustomToken table still exists)
    """
    print("⚠️  Reverse migration not implemented - please restore from backup if needed")


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_nursespecialization_alter_user_managers_and_more'),
        ('authtoken', '__latest__'),  # Ensure authtoken app is migrated first
    ]

    operations = [
        migrations.RunPython(migrate_custom_tokens_to_drf, reverse_migration),
    ]
