# Generated by Django 4.2.26 on 2025-12-05 09:50
# Delete CustomToken model and table after data migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_migrate_tokens_to_drf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
