# Generated by Django 4.2.26 on 2026-01-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_delete_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctors', to='common.clinic', verbose_name='Основная клиника'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_nurses', to='common.clinic', verbose_name='Основная клиника'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='common.clinic', verbose_name='Дополнительные клиники'),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='nurses', to='common.clinic', verbose_name='Дополнительные клиники'),
        ),
    ]
