# Generated by Django 4.2.26 on 2026-01-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinics_created_at_clinics_is_deleted_and_more'),
        ('common', '0023_doctorprofile_clinic_nurseprofile_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='clinics',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='clinics',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='additional_clinics',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='clinics.clinics', verbose_name='Дополнительные клиники'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='additional_clinics',
            field=models.ManyToManyField(blank=True, related_name='nurses', to='clinics.clinics', verbose_name='Дополнительные клиники'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctors', to='clinics.clinics', verbose_name='Основная клиника'),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_nurses', to='clinics.clinics', verbose_name='Основная клиника'),
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
