# Generated by Django 4.2.26 on 2026-01-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinics_created_at_clinics_is_deleted_and_more'),
        ('common', '0024_remove_doctorprofile_clinics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='clinics.clinics', verbose_name='Клиника'),
        ),
    ]
