# Generated by Django 4.2.26 on 2026-01-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_user_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('medicine', models.CharField(max_length=255)),
                ('mkb', models.CharField(max_length=50)),
                ('mkb_codes', models.JSONField(default=list)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('extension', models.CharField(max_length=10)),
                ('modified', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клинический протокол',
                'verbose_name_plural': 'Клинические протоколы',
                'db_table': 'common_clinical_protocols',
            },
        ),
    ]
