# Generated by Django 4.2.26 on 2026-01-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_clinicalprotocol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinicalProtocol',
        ),
    ]
