# Generated by Django 4.2.27 on 2026-02-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_add_user_session_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_specializations',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='common.doctorspecialization', verbose_name='Специализации врача'),
        ),
        migrations.AddField(
            model_name='user',
            name='nurse_specializations',
            field=models.ManyToManyField(blank=True, related_name='nurses', to='common.nursespecialization', verbose_name='Специализации медсестры'),
        ),
        migrations.AlterField(
            model_name='user',
            name='doctor_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.doctorspecialization', verbose_name='Специализация врача (основная)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nurse_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.nursespecialization', verbose_name='Специализация медсестры (основная)'),
        ),
    ]
