# Generated by Django 4.2.27 on 2026-02-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_user_doctor_specializations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='offline_consultation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена офлайн консультации'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='online_consultation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена онлайн консультации'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='preferred_consultation_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность консультации (мин)'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='work_schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Расписание работы'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='offline_consultation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена офлайн консультации'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='online_consultation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена онлайн консультации'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='preferred_consultation_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность консультации (мин)'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='work_schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Расписание работы'),
        ),
    ]
