# Generated by Django 4.2.27 on 2026-02-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_add_consultation_and_schedule_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='clinic',
        ),
    ]
