# Generated by Django 4.2.27 on 2026-02-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_remove_clinic_from_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='offline_work_schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Расписание работы (Оффлайн консультации)'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='online_work_schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Расписание работы (Онлайн консультации)'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='offline_work_schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Расписание работы (Оффлайн консультации)'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='online_work_schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Расписание работы (Онлайн консультации)'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='work_schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Расписание работы (Онлайн)'),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='work_schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Расписание работы (Онлайн)'),
        ),
    ]
