# Generated by Django 4.2.27 on 2026-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_doctorprofile_offline_work_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Языки'),
        ),
    ]
