# Generated by Django 4.2.28 on 2026-02-07 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_migrate_to_abstractbaseuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='Группа крови')),
                ('rhesus_factor', models.CharField(blank=True, choices=[('positive', 'Положительный'), ('negative', 'Отрицательный')], max_length=10, null=True, verbose_name='Резус-фактор')),
                ('fluorography_status', models.CharField(blank=True, choices=[('normal', 'Норма'), ('abnormal', 'Отклонения'), ('pending', 'Ожидает результата'), ('expired', 'Просрочена')], max_length=20, null=True, verbose_name='Статус флюорографии')),
                ('fluorography_date', models.DateField(blank=True, null=True, verbose_name='Дата флюорографии')),
                ('immunization_status', models.CharField(blank=True, choices=[('up_to_date', 'Актуальная'), ('partial', 'Частичная'), ('expired', 'Просрочена'), ('none', 'Отсутствует')], max_length=20, null=True, verbose_name='Статус иммунизации')),
                ('immunization_date', models.DateField(blank=True, null=True, verbose_name='Дата последней иммунизации')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_medical_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Последнее изменение')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Медицинский профиль пациента',
                'verbose_name_plural': 'Медицинские профили пациентов',
                'db_table': 'patient_medical_profiles',
                'permissions': [('view_own_medical_profile', 'Can view own medical profile'), ('view_patient_medical_profile', 'Can view patient medical profiles'), ('modify_patient_medical_profile', 'Can modify patient medical profiles')],
            },
        ),
    ]
