# Generated by Django 4.2.28 on 2026-02-07 22:18

from django.db import migrations


def migrate_medical_data_forward(apps, schema_editor):
    """
    Copy medical data from User to PatientMedicalProfile for all patients.
    Only creates profiles for patients who have any medical data.
    """
    User = apps.get_model('common', 'User')
    PatientMedicalProfile = apps.get_model('common', 'PatientMedicalProfile')

    patients = User.objects.filter(role='patient')
    created_count = 0
    skipped_count = 0

    for patient in patients:
        # Only create profile if patient has any medical data
        has_medical_data = any([
            patient.blood_type,
            patient.rhesus_factor,
            patient.fluorography_status,
            patient.fluorography_date,
            patient.immunization_status,
            patient.immunization_date,
        ])

        if has_medical_data:
            # Check if profile already exists
            if not PatientMedicalProfile.objects.filter(user=patient).exists():
                PatientMedicalProfile.objects.create(
                    user=patient,
                    blood_type=patient.blood_type,
                    rhesus_factor=patient.rhesus_factor,
                    fluorography_status=patient.fluorography_status,
                    fluorography_date=patient.fluorography_date,
                    immunization_status=patient.immunization_status,
                    immunization_date=patient.immunization_date,
                    # Keep audit trail
                    created_at=patient.created_at,
                    updated_at=patient.updated_at,
                )
                created_count += 1
        else:
            skipped_count += 1

    print(f"\n{'='*60}")
    print(f"Medical Data Migration Complete")
    print(f"{'='*60}")
    print(f"✓ Total patients: {patients.count()}")
    print(f"✓ Profiles created: {created_count}")
    print(f"✓ Skipped (no medical data): {skipped_count}")
    print(f"{'='*60}\n")


def migrate_medical_data_backward(apps, schema_editor):
    """
    Reverse migration: Copy data back from PatientMedicalProfile to User.
    This allows us to rollback if needed.
    """
    User = apps.get_model('common', 'User')
    PatientMedicalProfile = apps.get_model('common', 'PatientMedicalProfile')

    profiles = PatientMedicalProfile.objects.all()
    updated_count = 0

    for profile in profiles:
        user = profile.user
        user.blood_type = profile.blood_type
        user.rhesus_factor = profile.rhesus_factor
        user.fluorography_status = profile.fluorography_status
        user.fluorography_date = profile.fluorography_date
        user.immunization_status = profile.immunization_status
        user.immunization_date = profile.immunization_date
        user.save()
        updated_count += 1

    print(f"\n{'='*60}")
    print(f"Medical Data Rollback Complete")
    print(f"{'='*60}")
    print(f"✓ Users updated: {updated_count}")
    print(f"{'='*60}\n")


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_create_patient_medical_profile'),
    ]

    operations = [
        migrations.RunPython(
            migrate_medical_data_forward,
            migrate_medical_data_backward
        ),
    ]
