# Generated by Django 4.2.28 on 2026-02-07 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinics_created_at_clinics_is_deleted_and_more'),
        ('common', '0036_migrate_medical_data_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='availability_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметка о доступности'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available', 'Доступен'), ('busy', 'Занят'), ('offline', 'Не работает'), ('break', 'На перерыве')], default='offline', max_length=20, null=True, verbose_name='Статус доступности'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctors', to='clinics.clinics', verbose_name='Основная клиника'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип врача'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='doctors_multi', to='common.doctorspecialization', verbose_name='Все специализации'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='availability_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметка о доступности'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available', 'Доступен'), ('busy', 'Занят'), ('offline', 'Не работает'), ('break', 'На перерыве')], default='offline', max_length=20, null=True, verbose_name='Статус доступности'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_nurses', to='clinics.clinics', verbose_name='Основная клиника'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='nurse_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип медсестры'),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='nurses_multi', to='common.nursespecialization', verbose_name='Все специализации'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.doctorspecialization', verbose_name='Основная специализация'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.nursespecialization', verbose_name='Основная специализация'),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='doctorprofile',
            table='doctor_profiles',
        ),
        migrations.AlterModelTable(
            name='nurseprofile',
            table='nurse_profiles',
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('citizenship', models.CharField(blank=True, default='Казахстан', max_length=100, null=True, verbose_name='Гражданство')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Не женат/не замужем'), ('married', 'Женат/замужем'), ('divorced', 'Разведен/разведена'), ('widowed', 'Вдовец/вдова')], max_length=20, null=True, verbose_name='Семейное положение')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя контакта для экстренных случаев')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон экстренного контакта')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отношение экстренного контакта')),
                ('preferred_language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Предпочитаемый язык')),
                ('communication_preferences', models.JSONField(blank=True, default=dict, null=True, verbose_name='Предпочтения связи')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Профиль пациента',
                'verbose_name_plural': 'Профили пациентов',
                'db_table': 'patient_profiles',
            },
        ),
    ]
