# Generated by Django 4.2.28 on 2026-02-08 00:40

from django.db import migrations


def migrate_doctor_data_forward(apps, schema_editor):
    """
    Migrate doctor-specific data from User model to DoctorProfile.
    Updates existing DoctorProfile or creates new ones.
    """
    User = apps.get_model('common', 'User')
    DoctorProfile = apps.get_model('common', 'DoctorProfile')

    doctors = User.objects.filter(role='doctor')
    created_count = 0
    updated_count = 0

    print(f"\n{'='*70}")
    print(f"Migrating Doctor Data to DoctorProfile")
    print(f"{'='*70}")
    print(f"Found {doctors.count()} doctors")

    for doctor in doctors:
        # Get or create doctor profile
        profile, created = DoctorProfile.objects.get_or_create(
            user=doctor,
            defaults={
                'doctor_type': doctor.doctor_type,
                'specialization': doctor.doctor_specialization,
                'clinic': doctor.clinic,
                'availability_status': doctor.availability_status or 'offline',
                'availability_note': doctor.availability_note,
                'created_at': doctor.created_at,
                'updated_at': doctor.updated_at,
            }
        )

        if created:
            # Set M2M fields after creation
            if doctor.doctor_specializations.exists():
                profile.specializations.set(doctor.doctor_specializations.all())
            created_count += 1
            print(f"  ✓ Created profile for Dr. {doctor.first_name} {doctor.last_name}")
        else:
            # Update existing profile
            profile.doctor_type = doctor.doctor_type
            profile.specialization = doctor.doctor_specialization
            profile.clinic = doctor.clinic
            profile.availability_status = doctor.availability_status or profile.availability_status
            profile.availability_note = doctor.availability_note
            profile.save()

            # Update M2M fields
            if doctor.doctor_specializations.exists():
                profile.specializations.set(doctor.doctor_specializations.all())

            updated_count += 1
            print(f"  ↻ Updated profile for Dr. {doctor.first_name} {doctor.last_name}")

    print(f"\n{'='*70}")
    print(f"Doctor Data Migration Complete")
    print(f"{'='*70}")
    print(f"✓ Profiles created: {created_count}")
    print(f"✓ Profiles updated: {updated_count}")
    print(f"✓ Total processed: {created_count + updated_count}")
    print(f"{'='*70}\n")


def migrate_doctor_data_backward(apps, schema_editor):
    """
    Reverse migration: Copy data back from DoctorProfile to User.
    """
    User = apps.get_model('common', 'User')
    DoctorProfile = apps.get_model('common', 'DoctorProfile')

    profiles = DoctorProfile.objects.all()
    updated_count = 0

    for profile in profiles:
        user = profile.user
        user.doctor_type = profile.doctor_type
        user.doctor_specialization = profile.specialization
        user.clinic = profile.clinic
        user.availability_status = profile.availability_status
        user.availability_note = profile.availability_note
        user.save()

        # Copy M2M fields
        if profile.specializations.exists():
            user.doctor_specializations.set(profile.specializations.all())

        updated_count += 1

    print(f"\n✓ Rolled back {updated_count} doctor profiles to User model\n")


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_update_role_based_profiles'),
        ('clinics', '__latest__'),  # Ensure clinics app is migrated
    ]

    operations = [
        migrations.RunPython(
            migrate_doctor_data_forward,
            migrate_doctor_data_backward
        ),
    ]
