# Generated by Django 4.2.28 on 2026-02-08 00:42

from django.db import migrations


def migrate_nurse_data_forward(apps, schema_editor):
    """
    Migrate nurse-specific data from User model to NurseProfile.
    Updates existing NurseProfile or creates new ones.
    """
    User = apps.get_model('common', 'User')
    NurseProfile = apps.get_model('common', 'NurseProfile')

    nurses = User.objects.filter(role='nurse')
    created_count = 0
    updated_count = 0

    print(f"\n{'='*70}")
    print(f"Migrating Nurse Data to NurseProfile")
    print(f"{'='*70}")
    print(f"Found {nurses.count()} nurses")

    for nurse in nurses:
        # Get or create nurse profile
        profile, created = NurseProfile.objects.get_or_create(
            user=nurse,
            defaults={
                'nurse_type': nurse.nurse_type,
                'specialization': nurse.nurse_specialization,
                'clinic': nurse.clinic,
                'availability_status': nurse.availability_status or 'offline',
                'availability_note': nurse.availability_note,
                'created_at': nurse.created_at,
                'updated_at': nurse.updated_at,
            }
        )

        if created:
            # Set M2M fields after creation
            if nurse.nurse_specializations.exists():
                profile.specializations.set(nurse.nurse_specializations.all())
            created_count += 1
            print(f"  ✓ Created profile for Nurse {nurse.first_name} {nurse.last_name}")
        else:
            # Update existing profile
            profile.nurse_type = nurse.nurse_type
            profile.specialization = nurse.nurse_specialization
            profile.clinic = nurse.clinic
            profile.availability_status = nurse.availability_status or profile.availability_status
            profile.availability_note = nurse.availability_note
            profile.save()

            # Update M2M fields
            if nurse.nurse_specializations.exists():
                profile.specializations.set(nurse.nurse_specializations.all())

            updated_count += 1
            print(f"  ↻ Updated profile for Nurse {nurse.first_name} {nurse.last_name}")

    print(f"\n{'='*70}")
    print(f"Nurse Data Migration Complete")
    print(f"{'='*70}")
    print(f"✓ Profiles created: {created_count}")
    print(f"✓ Profiles updated: {updated_count}")
    print(f"✓ Total processed: {created_count + updated_count}")
    print(f"{'='*70}\n")


def migrate_nurse_data_backward(apps, schema_editor):
    """
    Reverse migration: Copy data back from NurseProfile to User.
    """
    User = apps.get_model('common', 'User')
    NurseProfile = apps.get_model('common', 'NurseProfile')

    profiles = NurseProfile.objects.all()
    updated_count = 0

    for profile in profiles:
        user = profile.user
        user.nurse_type = profile.nurse_type
        user.nurse_specialization = profile.specialization
        user.clinic = profile.clinic
        user.availability_status = profile.availability_status
        user.availability_note = profile.availability_note
        user.save()

        # Copy M2M fields
        if profile.specializations.exists():
            user.nurse_specializations.set(profile.specializations.all())

        updated_count += 1

    print(f"\n✓ Rolled back {updated_count} nurse profiles to User model\n")


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_migrate_doctor_data_to_profile'),
        ('clinics', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            migrate_nurse_data_forward,
            migrate_nurse_data_backward
        ),
    ]
