# Generated by Django 4.2.28 on 2026-02-08 00:42

from django.db import migrations


def migrate_patient_data_forward(apps, schema_editor):
    """
    Migrate patient-specific data from User model to PatientProfile.
    Updates existing PatientProfile or creates new ones.
    """
    User = apps.get_model('common', 'User')
    PatientProfile = apps.get_model('common', 'PatientProfile')

    patients = User.objects.filter(role='patient')
    created_count = 0
    updated_count = 0

    print(f"\n{'='*70}")
    print(f"Migrating Patient Data to PatientProfile")
    print(f"{'='*70}")
    print(f"Found {patients.count()} patients")

    for patient in patients:
        # Get or create patient profile
        profile, created = PatientProfile.objects.get_or_create(
            user=patient,
            defaults={
                'citizenship': patient.citizenship or 'Казахстан',
                'marital_status': patient.marital_status,
                'profession': patient.profession,
                'created_at': patient.created_at,
                'updated_at': patient.updated_at,
            }
        )

        if created:
            created_count += 1
            print(f"  ✓ Created profile for Patient {patient.first_name} {patient.last_name}")
        else:
            # Update existing profile
            profile.citizenship = patient.citizenship or profile.citizenship
            profile.marital_status = patient.marital_status or profile.marital_status
            profile.profession = patient.profession or profile.profession
            profile.save()

            updated_count += 1
            print(f"  ↻ Updated profile for Patient {patient.first_name} {patient.last_name}")

    print(f"\n{'='*70}")
    print(f"Patient Data Migration Complete")
    print(f"{'='*70}")
    print(f"✓ Profiles created: {created_count}")
    print(f"✓ Profiles updated: {updated_count}")
    print(f"✓ Total processed: {created_count + updated_count}")
    print(f"{'='*70}\n")


def migrate_patient_data_backward(apps, schema_editor):
    """
    Reverse migration: Copy data back from PatientProfile to User.
    """
    User = apps.get_model('common', 'User')
    PatientProfile = apps.get_model('common', 'PatientProfile')

    profiles = PatientProfile.objects.all()
    updated_count = 0

    for profile in profiles:
        user = profile.user
        user.citizenship = profile.citizenship
        user.marital_status = profile.marital_status
        user.profession = profile.profession
        user.save()

        updated_count += 1

    print(f"\n✓ Rolled back {updated_count} patient profiles to User model\n")


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_migrate_nurse_data_to_profile'),
    ]

    operations = [
        migrations.RunPython(
            migrate_patient_data_forward,
            migrate_patient_data_backward
        ),
    ]
