# Generated by Django 4.2.28 on 2026-02-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_migrate_patient_data_to_profile'),
    ]

    operations = [
    ]
