# Generated by Django 4.2.28 on 2026-02-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_remove_deprecated_user_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='availability_note',
        ),
        migrations.RemoveField(
            model_name='user',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doctor_specialization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doctor_specializations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doctor_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fluorography_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fluorography_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='immunization_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='immunization_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nurse_specialization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nurse_specializations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nurse_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rhesus_factor',
        ),
    ]
