# Generated by Django 4.2.28 on 2026-02-08 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinics_created_at_clinics_is_deleted_and_more'),
        ('common', '0042_remove_user_availability_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('admin_type', models.CharField(blank=True, choices=[('super', 'Супер администратор'), ('clinic', 'Администратор клиники'), ('manager', 'Менеджер')], default='clinic', max_length=50, null=True, verbose_name='Тип администратора')),
                ('can_manage_staff', models.BooleanField(default=True, verbose_name='Может управлять персоналом')),
                ('can_manage_patients', models.BooleanField(default=True, verbose_name='Может управлять пациентами')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='Может просматривать отчеты')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='Может управлять настройками')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отдел')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='clinics.clinics', verbose_name='Клиника')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Профиль администратора',
                'verbose_name_plural': 'Профили администраторов',
                'db_table': 'admin_profiles',
            },
        ),
    ]
