# Generated by Django 4.2.28 on 2026-02-08 13:57

from django.db import migrations


def migrate_admin_data_forward(apps, schema_editor):
    """
    Create AdminProfile for all existing admin users.
    By default, make them super admins (no clinic restriction).
    """
    User = apps.get_model('common', 'User')
    AdminProfile = apps.get_model('common', 'AdminProfile')

    admins = User.objects.filter(role='admin')
    created_count = 0
    updated_count = 0

    print(f"\n{'='*70}")
    print(f"Migrating Admin Data to AdminProfile")
    print(f"{'='*70}")
    print(f"Found {admins.count()} admins")

    for admin in admins:
        # Create admin profile - default to super admin (no clinic)
        profile, created = AdminProfile.objects.get_or_create(
            user=admin,
            defaults={
                'clinic': None,  # Super admin by default
                'admin_type': 'super',
                'can_manage_staff': True,
                'can_manage_patients': True,
                'can_view_reports': True,
                'can_manage_settings': True,
                'created_at': admin.created_at,
                'updated_at': admin.updated_at,
            }
        )

        if created:
            created_count += 1
            print(f"  ✓ Created super admin profile for {admin.first_name} {admin.last_name}")
        else:
            updated_count += 1
            print(f"  ↻ Admin profile already exists for {admin.first_name} {admin.last_name}")

    print(f"\n{'='*70}")
    print(f"Admin Data Migration Complete")
    print(f"{'='*70}")
    print(f"✓ Profiles created: {created_count}")
    print(f"✓ Profiles updated: {updated_count}")
    print(f"✓ Total processed: {created_count + updated_count}")
    print(f"{'='*70}\n")


def migrate_admin_data_backward(apps, schema_editor):
    """
    Reverse migration: Delete all admin profiles.
    """
    AdminProfile = apps.get_model('common', 'AdminProfile')

    deleted_count = AdminProfile.objects.count()
    AdminProfile.objects.all().delete()

    print(f"\n✓ Rolled back {deleted_count} admin profiles\n")


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_adminprofile'),
    ]

    operations = [
        migrations.RunPython(
            migrate_admin_data_forward,
            migrate_admin_data_backward
        ),
    ]
