# Generated by Django 4.2.28 on 2026-02-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_migrate_admin_data_to_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminprofile',
            table='common_admin_profiles',
        ),
        migrations.AlterModelTable(
            name='doctorprofile',
            table='common_doctor_profiles',
        ),
        migrations.AlterModelTable(
            name='nurseprofile',
            table='common_nurse_profiles',
        ),
        migrations.AlterModelTable(
            name='patientmedicalprofile',
            table='common_patient_medical_profiles',
        ),
        migrations.AlterModelTable(
            name='patientprofile',
            table='common_patient_profiles',
        ),
    ]
