# Generated by Django 4.2.28 on 2026-02-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_alter_adminprofile_table_alter_doctorprofile_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='preferred_consultation_duration',
            field=models.PositiveIntegerField(default=30, verbose_name='Длительность консультации (мин)'),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='preferred_consultation_duration',
            field=models.PositiveIntegerField(default=30, verbose_name='Длительность консультации (мин)'),
        ),
    ]
