# Generated by Django 4.2.28 on 2026-02-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_clinics_created_at_clinics_is_deleted_and_more'),
        ('common', '0046_make_consultation_duration_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='clinics.clinics', verbose_name='Клиника'),
        ),
    ]
