# Generated by Django 4.2.23 on 2025-07-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Уникальное имя игрока', max_length=100, unique=True, verbose_name='Никнейм')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'db_table': 'ai_game_player',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='Описание симптомов для диагноза', verbose_name='Симптомы')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('wrong_answers', models.JSONField(help_text='JSON-массив неправильных вариантов', verbose_name='Неправильные ответы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'ai_game_question',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Количество правильных ответов', verbose_name='Очки')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('ended_at', models.DateTimeField(auto_now=True, verbose_name='Время окончания')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ai_game.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'db_table': 'ai_game_session',
            },
        ),
    ]
