# Generated by Django 4.2.27 on 2026-01-24 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_level', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Уровень сахара (ммоль/л)')),
                ('systolic_pressure', models.PositiveIntegerField(verbose_name='Систолическое давление (мм рт. ст.)')),
                ('diastolic_pressure', models.PositiveIntegerField(verbose_name='Диастолическое давление (мм рт. ст.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_questionnaires', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анкета здоровья',
                'verbose_name_plural': 'Анкеты здоровья',
                'db_table': 'questionnaire_health',
                'ordering': ['-created_at'],
            },
        ),
    ]
