# Generated by Django 5.1.2 on 2025-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="consultation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
