# Generated by Django 4.2.21 on 2025-06-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_is_deleted_consultation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('ongoing', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('missed', 'Пропущено')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
