# Generated by Django 4.2.21 on 2025-06-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_user_doctor_type'),
        ('consultations', '0003_alter_consultation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('symptoms', models.TextField(verbose_name='Симптомы запроса')),
                ('ai_raw_response', models.TextField(verbose_name='Сырой ответ AI')),
                ('recommended_specialty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рекомендованная специализация')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Пояснение AI')),
                ('fallback_used', models.BooleanField(default=False, verbose_name='Использован fallback (терапевт)?')),
                ('specialty_not_found', models.CharField(blank=True, max_length=255, null=True, verbose_name='Найденная AI специализация, но врач не найден')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_matches', to='common.user', verbose_name='Назначенный врач')),
            ],
            options={
                'verbose_name': 'Лог AI-рекомендации',
                'verbose_name_plural': 'Логи AI-рекомендаций',
                'db_table': 'consultations_ai_recommendation_logs',
            },
        ),
    ]
