# Generated by Django 4.2.23 on 2025-07-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_airecommendationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Экстренность консультации'),
        ),
    ]
