# Generated by Django 4.2.23 on 2025-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendationlog',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Экстренность рекомендации AI'),
        ),
    ]
