# Generated by Django 4.2.23 on 2025-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_airecommendationlog_is_urgent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airecommendationlog',
            name='is_urgent',
        ),
        migrations.AddField(
            model_name='airecommendationlog',
            name='urgency',
            field=models.CharField(choices=[('urgent', 'Экстренная'), ('non_urgent', 'Не экстренная')], default='non_urgent', max_length=10, verbose_name='Экстренность рекомендации AI'),
        ),
    ]
