# Generated by Django 4.2.24 on 2025-09-18 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0007_remove_airecommendationlog_is_urgent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ai_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='consultations.airecommendationlog', verbose_name='AI рекомендация'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланированное время'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('ongoing', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('missed', 'Пропущено'), ('scheduled', 'Запланировано')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('max_consultations', models.PositiveIntegerField(default=1, verbose_name='Максимум консультаций')),
                ('booked_consultations', models.PositiveIntegerField(default=0, verbose_name='Забронированные консультации')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Повторяющийся слот')),
                ('recurrence_type', models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=10, null=True, verbose_name='Тип повторения')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания повторения')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_timeslots', to=settings.AUTH_USER_MODEL, verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
                'db_table': 'consultation_timeslots',
                'ordering': ['start_time'],
                'unique_together': {('doctor', 'start_time', 'end_time')},
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='consultations.timeslot', verbose_name='Временной слот'),
        ),
    ]
