# Generated by Django 4.2.26 on 2025-11-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_consultation_ai_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='anamnesis',
            field=models.TextField(blank=True, null=True, verbose_name='Анамнез'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='complaints',
            field=models.TextField(blank=True, null=True, verbose_name='Жалобы пациента'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Диагноз'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='diagnostics',
            field=models.TextField(blank=True, null=True, verbose_name='Диагностика'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='treatment',
            field=models.TextField(blank=True, null=True, verbose_name='Лечение и рекомендации'),
        ),
    ]
