# Generated by Django 4.2.26 on 2025-11-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_consultation_anamnesis_consultation_complaints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.TextField(blank=True, null=True, verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендации'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='session_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки консультации'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='transcription',
            field=models.TextField(blank=True, null=True, verbose_name='Транскрипция'),
        ),
    ]
