# Generated by Django 4.2.28 on 2026-02-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0011_add_access_code_to_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='magic_link_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время использования магической ссылки'),
        ),
    ]
