# Generated by Django 5.1.2 on 2024-10-11 11:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDistrictAkim',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=255, verbose_name='Фото акима')),
                ('name_kz', models.CharField(max_length=255, verbose_name='Фото акима')),
                ('akim_img', models.CharField(max_length=255, verbose_name='Фото акима')),
                ('date_of_appointment', models.DateField(verbose_name='Фото акима')),
                ('date_of_dismissal', models.DateField(verbose_name='Фото акима')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Аким города или района города',
                'verbose_name_plural': 'Акимы городов или районов городов',
                'db_table': 'address_city_district_akims',
            },
        ),
        migrations.CreateModel(
            name='CityDistrict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_kz', models.CharField(max_length=255, verbose_name='Название на казахском')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('response_name_kz', models.CharField(max_length=255, verbose_name='Произношение на казахском')),
                ('response_name_ru', models.CharField(max_length=255, verbose_name='Произношение на русском')),
                ('gerb_img', models.CharField(max_length=255, verbose_name='Герб')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Геометрия')),
                ('marker', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Маркер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('akim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='address.citydistrictakim', verbose_name='Аким')),
            ],
            options={
                'verbose_name': 'Район города',
                'verbose_name_plural': 'Районы городов',
                'db_table': 'address_city_districts',
            },
        ),
    ]
