# Generated by Django 5.1.2 on 2024-10-23 14:34

import colorful.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microsectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('name_kz', models.CharField(max_length=100, verbose_name='Название на казахском')),
                ('line_color', colorful.fields.RGBColorField(help_text='Выберите цвет линии', verbose_name='Цвет линии')),
                ('fill_color', colorful.fields.RGBColorField(help_text='Выберите цвет заливки', verbose_name='Цвет заливки')),
                ('opacity', models.FloatField(help_text='Прозрачность от 0 до 1', verbose_name='Прозрачность')),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Границы на карте')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Граница микроучастка',
                'verbose_name_plural': 'Границы микроучастков',
                'db_table': 'address_microsectors',
            },
        ),
    ]
