# Generated by Django 5.1.2 on 2024-10-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_microsectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydistrict',
            name='gerb_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Герб'),
        ),
        migrations.AlterField(
            model_name='citydistrict',
            name='name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на казахском'),
        ),
        migrations.AlterField(
            model_name='citydistrict',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='citydistrict',
            name='response_name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Произношение на казахском'),
        ),
        migrations.AlterField(
            model_name='citydistrict',
            name='response_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Произношение на русском'),
        ),
    ]
