# Generated by Django 5.1.2 on 2024-11-06 11:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_livingzones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsectors',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Границы на карте'),
        ),
    ]
