# Generated by Django 4.2.21 on 2025-05-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_user_is_staff_user_is_superuser'),
        ('appointments', '0002_appointment_is_deleted_appointment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('appointment_time', models.DateTimeField(verbose_name='Дата и время вызова')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес вызова')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Симптомы')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_doctor_appointments', to='common.user', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_appointments', to='common.user', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Вызов на дом',
                'verbose_name_plural': 'Вызовы на дом',
                'db_table': 'appointment_home',
                'ordering': ['-appointment_time'],
                'unique_together': {('doctor', 'appointment_time')},
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
