# Generated by Django 4.2.26 on 2025-11-15 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0003_homeappointment_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeappointment',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_nurse_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Медсестра'),
        ),
        migrations.AlterField(
            model_name='homeappointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('assigned', 'Назначено медсестре'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
    ]
