# Generated by Django 4.2.26 on 2025-11-15 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0004_homeappointment_nurse_alter_homeappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeappointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_doctor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
    ]
