# Generated by Django 4.2.26 on 2025-11-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_homeappointment_latitude_homeappointment_longitude'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeappointment',
            unique_together=set(),
        ),
    ]
