# Generated by Django 4.2.26 on 2025-11-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_homeappointment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeappointment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='homeappointment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True, verbose_name='Долгота'),
        ),
    ]
