# Generated by Django 4.2.26 on 2025-11-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_homeappointment_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeappointment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='homeappointment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=255, null=True, verbose_name='Долгота'),
        ),
    ]
