# Generated by Django 4.2.26 on 2025-11-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_homeappointment_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeappointment',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='homeappointment',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
