# Generated by Django 5.1.2 on 2024-10-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_kz', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Оперативная карточка',
                'verbose_name_plural': 'Оперативные карточки',
                'db_table': 'card101_operation_card',
            },
        ),
        migrations.CreateModel(
            name='Card101',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('object_name', models.CharField(max_length=255, verbose_name='Наименование объекта')),
                ('operation_plan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оперативный план')),
                ('constructive_features', models.TextField(blank=True, null=True, verbose_name='Конструктивные особенности')),
                ('year_of_construction', models.IntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('object_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь объекта')),
                ('floors', models.IntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('fire_floor', models.IntegerField(blank=True, null=True, verbose_name='На каком этаже пожар')),
                ('applicant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО Заявителя')),
                ('applicant_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон заявителя')),
                ('danger_to_people', models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет'), ('unknown', 'Неизвестно')], max_length=20, null=True, verbose_name='Опасность для людей')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.citydistrict', verbose_name='Район города')),
                ('operation_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card101.operationcard', verbose_name='Оперативная карточка')),
            ],
            options={
                'verbose_name': 'Карточка 101',
                'verbose_name_plural': 'Карточки 101',
                'db_table': 'card101',
            },
        ),
    ]
