# Generated by Django 5.1.2 on 2024-10-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card101', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('name_kz', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ранг пожара',
                'verbose_name_plural': 'Ранги пожара',
                'db_table': 'card101_fire_rank',
            },
        ),
        migrations.AddField(
            model_name='card101',
            name='fire_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card101.firerank', verbose_name='Ранг пожара'),
        ),
    ]
