# Generated by Django 5.1.2 on 2024-10-30 11:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_livingzones'),
        ('card101', '0002_firerank_card101_fire_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на русском')),
                ('name_kz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на казахском')),
                ('old_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (старое) на казахском')),
                ('use_in_recommendations', models.BooleanField(default=False, verbose_name='Использовать в рекомендациях')),
                ('use_in_buildings', models.BooleanField(default=False, verbose_name='Использовать в строевых')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='Сортировка')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Местоположение')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.citydistrict', verbose_name='Район города')),
            ],
            options={
                'verbose_name': 'Пожарная часть',
                'verbose_name_plural': 'Пожарные части',
                'db_table': 'card101_fire_stations',
            },
        ),
    ]
