# Generated by Django 5.1.2 on 2024-10-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card101', '0003_firestations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firestations',
            old_name='use_in_buildings',
            new_name='use_in_records',
        ),
    ]
