# Generated by Django 5.1.2 on 2024-10-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card101', '0004_rename_use_in_buildings_firestations_use_in_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestations',
            name='old_name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (старое) на казахском'),
        ),
        migrations.AlterField(
            model_name='firestations',
            name='old_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (старое) на русском'),
        ),
    ]
