# Generated by Django 4.2.26 on 2026-01-13 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_protocols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalProtocolContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('definition', 'Определение'), ('diagnosis', 'Диагностика'), ('classification', 'Классификация'), ('differential', 'Дифференциальный диагноз'), ('treatment', 'Лечение'), ('drugs', 'Лекарственные средства'), ('algorithm', 'Алгоритм ведения'), ('complications', 'Осложнения'), ('indications', 'Показания'), ('contraindications', 'Противопоказания'), ('other', 'Другое')], max_length=32)),
                ('title', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('page_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='pdf', help_text='Источник данных (pdf, guideline, update, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='clinical_protocols.clinicalprotocol')),
            ],
            options={
                'db_table': 'clinical_protocols_content',
                'ordering': ['protocol', 'content_type'],
                'indexes': [models.Index(fields=['protocol', 'content_type'], name='clinical_pr_protoco_6ce3f3_idx')],
            },
        ),
    ]
