# Generated by Django 4.2.26 on 2026-01-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_protocols', '0002_clinicalprotocolcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalprotocol',
            options={'ordering': ['-year', 'name'], 'verbose_name': 'Клинический протокол', 'verbose_name_plural': 'Клинические протоколы'},
        ),
        migrations.AlterModelOptions(
            name='clinicalprotocolcontent',
            options={'ordering': ['protocol', 'content_type'], 'verbose_name': 'Контент клинического протокола', 'verbose_name_plural': 'Контент клинических протоколов'},
        ),
        migrations.AddConstraint(
            model_name='clinicalprotocolcontent',
            constraint=models.UniqueConstraint(fields=('protocol', 'content_type', 'title'), name='uniq_protocol_content_block'),
        ),
    ]
