# Generated by Django 4.2.26 on 2026-01-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_protocols', '0003_alter_clinicalprotocol_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalprotocol',
            name='medicine',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clinicalprotocol',
            name='mkb',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clinicalprotocol',
            name='mkb_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='source',
            field=models.CharField(default='pdf', max_length=50),
        ),
    ]
