# Generated by Django 4.2.26 on 2026-01-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_protocols', '0004_alter_clinicalprotocol_medicine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalprotocolcontent',
            options={'ordering': ['protocol', 'content_type', 'order'], 'verbose_name': 'Контент клинического протокола', 'verbose_name_plural': 'Контент клинических протоколов'},
        ),
        migrations.AddField(
            model_name='clinicalprotocolcontent',
            name='confidence',
            field=models.FloatField(default=1.0, help_text='Доверие к источнику (1.0 = оригинал из протокола)'),
        ),
        migrations.AddField(
            model_name='clinicalprotocolcontent',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Порядок внутри одного content_type'),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='content',
            field=models.TextField(help_text='Основной текст раздела'),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='content_type',
            field=models.CharField(choices=[('definition', 'Определение'), ('diagnosis', 'Диагностика'), ('classification', 'Классификация'), ('differential', 'Дифференциальный диагноз'), ('treatment', 'Лечение'), ('drugs', 'Лекарственные средства'), ('algorithm', 'Алгоритм ведения'), ('complications', 'Осложнения'), ('indications', 'Показания'), ('contraindications', 'Противопоказания'), ('references', 'Источники и литература'), ('meta', 'Организационная информация'), ('other', 'Другое')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='page_from',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Страница PDF (начало)', null=True),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='page_to',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Страница PDF (конец)', null=True),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='source',
            field=models.CharField(default='pdf', help_text='Источник данных: pdf / guideline / update / ai', max_length=50),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='title',
            field=models.TextField(blank=True, help_text='Заголовок раздела (если есть)'),
        ),
    ]
