# Generated by Django 4.2.26 on 2026-01-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_protocols', '0005_alter_clinicalprotocolcontent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalprotocolcontent',
            options={'ordering': ['protocol', 'content_type'], 'verbose_name': 'Контент клинического протокола', 'verbose_name_plural': 'Контент клинических протоколов'},
        ),
        migrations.RemoveField(
            model_name='clinicalprotocolcontent',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='clinicalprotocolcontent',
            name='order',
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='content_type',
            field=models.CharField(choices=[('definition', 'Определение'), ('diagnosis', 'Диагностика'), ('classification', 'Классификация'), ('differential', 'Дифференциальный диагноз'), ('treatment', 'Лечение'), ('drugs', 'Лекарственные средства'), ('algorithm', 'Алгоритм ведения'), ('complications', 'Осложнения'), ('indications', 'Показания'), ('contraindications', 'Противопоказания'), ('other', 'Другое')], max_length=32),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='page_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='page_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='source',
            field=models.CharField(default='pdf', max_length=50),
        ),
        migrations.AlterField(
            model_name='clinicalprotocolcontent',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
