# Generated by Django 4.2.27 on 2026-01-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_protocols', '0007_alter_clinicalprotocolcontent_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinicalProtocolContent',
        ),
    ]
