# Generated by Django 4.2.27 on 2026-01-13 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_protocols', '0008_delete_clinicalprotocolcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalProtocolContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('definition', 'Определение'), ('diagnosis', 'Диагностика'), ('classification', 'Классификация'), ('differential', 'Дифференциальный диагноз'), ('treatment', 'Лечение'), ('drugs', 'Лекарственные средства'), ('algorithm', 'Алгоритм ведения'), ('complications', 'Осложнения'), ('indications', 'Показания'), ('contraindications', 'Противопоказания'), ('references', 'Источники и литература'), ('meta', 'Организационная информация'), ('other', 'Другое')], db_index=True, max_length=32)),
                ('title', models.TextField(blank=True, help_text='Заголовок раздела (если есть)')),
                ('content', models.TextField(help_text='Основной текст раздела')),
                ('page_from', models.PositiveSmallIntegerField(blank=True, help_text='Страница PDF (начало)', null=True)),
                ('page_to', models.PositiveSmallIntegerField(blank=True, help_text='Страница PDF (конец)', null=True)),
                ('source', models.CharField(default='pdf', help_text='Источник данных: pdf / guideline / update / ai', max_length=50)),
                ('confidence', models.FloatField(default=1.0, help_text='Доверие к источнику (1.0 = оригинал из протокола)')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок внутри одного content_type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='clinical_protocols.clinicalprotocol')),
            ],
            options={
                'verbose_name': 'Контент клинического протокола',
                'verbose_name_plural': 'Контент клинических протоколов',
                'db_table': 'clinical_protocols_content',
                'ordering': ['protocol', 'content_type', 'order'],
                'indexes': [models.Index(fields=['protocol', 'content_type'], name='clinical_pr_protoco_6ce3f3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='clinicalprotocolcontent',
            constraint=models.UniqueConstraint(fields=('protocol', 'content_type', 'title'), name='uniq_protocol_content_block'),
        ),
    ]
