# Generated by Django 4.2.28 on 2026-03-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('preview', 'Preview'), ('import', 'Import'), ('delete', 'Delete')], max_length=32)),
                ('filename', models.CharField(blank=True, max_length=512)),
                ('gu_id', models.CharField(blank=True, max_length=128)),
                ('gu_name', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512)),
                ('gu_id', models.CharField(blank=True, max_length=128)),
                ('gu_name', models.CharField(blank=True, max_length=512)),
                ('record_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('skip_reason', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('was_edited', models.BooleanField(default=False)),
                ('general_provisions', models.TextField(blank=True)),
                ('tasks', models.JSONField(default=list)),
                ('authorities_rights', models.JSONField(default=list)),
                ('authorities_responsibilities', models.JSONField(default=list)),
                ('functions', models.JSONField(default=list)),
                ('additions', models.TextField(blank=True)),
                ('tasks_count', models.IntegerField(default=0)),
                ('rights_count', models.IntegerField(default=0)),
                ('responsibilities_count', models.IntegerField(default=0)),
                ('functions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
